apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: img-updater-bot-deployment
  namespace: flux-system
spec:
  images:
  - name: ghcr.io/dodbham-gitops/img-updater-bot
    newTag: 0.0.1 # {"$imagepolicy": "flux-system:chalupa-bot-prod-image-policy:tag"}
    newName: ghcr.io/dodbham-gitops/img-updater-bot # {"$imagepolicy": "flux-system:chalupa-bot-prod-image-policy:name"}
  interval: 1m
  path: "./manifests"
  prune: true
  targetNamespace: img-updater
  sourceRef:
    kind: GitRepository
    name: image-updater-bot-repo
    namespace: flux-system
