apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: img-updater-bot-deployment
  namespace: flux-system
spec:
  images:
  - name: ghcr.io/dodbham-gitops/img-updater-bot
    newTag: release-0.0.3 # {"$imagepolicy": "flux-system:img-updater-bot-updater-policy:tag"}
    newName: ghcr.io/dodbham-gitops/img-updater-bot # {"$imagepolicy": "flux-system:img-updater-bot-updater-policy:name"}
  interval: 1m
  path: "./manifests"
  prune: true
  targetNamespace: img-updater
  sourceRef:
    kind: GitRepository
    name: img-updater-bot
    namespace: flux-system
